### PR TITLE
Fixed #194

### LINKED ISSUE #194: Questionnaire message on mobile
On the questionnaire page, when you click save progress, it gives you a message that your progress was saved. That message does not display correctly on a mobile device.

### PR DESCRIPTION
**Pull request by vector67**

### CODE REVIEW

**Comment by devosray** [comment]
@vector67  According to the files changed tab, you are removing `wiki/diagrams/Passwordactivity.png`. Is this correct?

**Comment by egeldenhuys** [comment]
While we are discussing the `wiki` directory in the main repo; the wiki is a repo on it's own. Images can be added to the wiki repository by cloning it locally.

**Comment by vector67** [comment]
Ok, I've fixed the file. I've also renamed it so that it goes with our naming scheme. When this gets pushed to master we need to rename the file on the wiki, so it doesn't break.

**Comment by devosray** [comment]
Much better!
image

**Pull request merged**
